### PR TITLE
WIP - DO NOT MERGE - Akka Cluster on Kubernetes with Istio

### PR DESCRIPTION
**Pull request by longshorej**
I'm not sure if we want this work to be in this project or somewhere else ultimately, but I'm putting it here for now.

This adds another Akka Cluster demo that has a focus on configuration for Kubernetes and deployment of an istio sidecar to terminate TLS for each port and ensure secure communications between nodes. There will also be an accompanying guide to complement the ones at https://github.com/typesafehub/prod-suite-management-doc/pulls

You'll need `minikube` and Istio installed and `istioctl` on your path to run `scripts/deploy-to-minikube`

It's still a WIP, not fully functioning.

### CODE REVIEW

**Comment by ktoso** [comment]
Very exciting! We'll likely want to publish this to the tech hub as a guide, I'm not sure it it can handle a sub directory in a repo or if this would want to be it's own repo, do you know @2m ?

**Comment by ktoso** [comment]
Looking forward to the readme / guide explaining the steps a bit more, but the script is looking very nice 👍

**Comment by ktoso** [comment]
@longshorej @fsat we talked a bit where this should live in the team and it would be best if it became an independent repo, though under the akka organisation - so like `akka-cluster-kubernetes-quickstart-scala` for example - I've created the repo right away so we can develop there right away https://github.com/akka/akka-cluster-kubernetes-quickstart-scala

The goal would be to have all these "get me started on ..." as repos and from there publish into the tech-hub etc. We'll handle updating versions of akka inside them etc.

Overall looks great, sooo looking forward to that :-)

**Comment by longshorej** [comment]
Sounds good - thanks @ktoso! I suspect it'll be a bit before I get back to this, as the Istio-related requirements are becoming more clear and I need to reach out to their mailing list to clarify a few things. But yeah, separate repo works for me, I didn't quite think it belonged here either :smile:

**Comment by ktoso** [comment]
Cool, thanks a ton - really looking forward to this one :)

**Pull request closed without merging**
