### PR TITLE
Fix & cleanup .travis.yml

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by 2m** [comment]
Now that the tests are running, the `akka-sample-fsm-java` is failing with compilation erro:

```
[ERROR] /home/travis/build/akka/akka-samples/akka-sample-fsm-java/src/main/java/sample/typed/Messages.java:[3,23] error: package akka.actor.typed does not exist
[ERROR] /home/travis/build/akka/akka-samples/akka-sample-fsm-java/src/main/java/sample/typed/Messages.java:[11,25] error: cannot find symbol
[ERROR]   symbol:   class ActorRef
  location: class Take
...
```

https://travis-ci.org/akka/akka-samples/jobs/521799560#L496

**Comment by dwijnand** [comment]
Indeed.  Looks like this needs fixes in some samples.

**Comment by raboof** [comment]
@dwijnand wow good observation! do you intend to pick this one up or would you like me to take over?

**Comment by dwijnand** [comment]
I suspected the CI setup was wrong and was proven right, but I don't have the bandwidth to fix it.  Please take it.

**Comment by raboof** [comment]
Will do! Thanks for highlighting the problem!

**Pull request closed without merging**
