### PR TITLE
Cleanup akka-sample-sharding

### PR DESCRIPTION
**Pull request by xirc**
- Fix typo
- Remove unused import

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by xirc** [comment]
> At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

I have verified my email address by following the procedure in the link.
Is there any other thing I should do?

**Comment by xirc** [comment]
> I have verified my email address by following the procedure in the link.
> Is there any other thing I should do?

https://github.com/akka/akka-samples/pull/235#issuecomment-708385960
I have agreed the CLA.

**Comment by raboof** [comment]
> > At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user
> 
> I have verified my email address by following the procedure in the link.
> Is there any other thing I should do?

Not sure what's going on, github indeed seems to link those commits to you just fine.

**Review by raboof — APPROVED** [review]

**Pull request merged**
